#!/usr/bin/env python3

import flask as _f
import setproctitle


HTTP_PORT = 8099
APP_NAME = "qumerki"
qapp = _f.Flask(APP_NAME, template_folder="www")


def main():
   qapp.run(host="0.0.0.0", port=HTTP_PORT, debug=False)


# -- -- entry point -- --
if __name__ == "__main__":
   setproctitle.setproctitle(APP_NAME)
   main()
